apiVersion: engine.kubevault.com/v1alpha1
kind: IgniteRole
metadata:
  name: ignite-superuser-role
  namespace: demo
spec:
  secretEngineRef:
    name: ignite-engine
  creationStatements:
    - CREATE USER "{{name}}" WITH PASSWORD '{{password}}';
  revocationStatements:
    - DROP USER "{{name}}";
  defaultTTL: 1h
  maxTTL: 24h
