apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: ignite-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  ignite:
    databaseRef:
      name: ignite
      namespace: demo
    pluginName: ignite-database-plugin
    allowedRoles:
      - "*"
    insecure: false
