apiVersion: engine.kubevault.com/v1alpha1
kind: DatabaseAccessRequest
metadata:
  name: mongo-cred-rqst
  namespace: demo
spec:
  roleRef:
    kind: MongoDBRole
    name: mongo-superuser-role
    namespace: demo
  subjects:
    - kind: ServiceAccount
      name: demo-sa
      namespace: demo