apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicy
metadata:
  name: mongo-reader-policy
  namespace: demo
spec:
  vaultRef:
    name: vault
  policyDocument: |
    path "your-database-path/creds/k8s.-.demo.mongo-superuser-role" {
      capabilities = ["read"]
    }
