apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: mongo-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  mongodb:
    databaseRef:
      name: mongodb
      namespace: demo
    pluginName: "mongodb-database-plugin"
