apiVersion: engine.kubevault.com/v1alpha1
kind: MongoDBRole
metadata:
  name: mongo-superuser-role
  namespace: demo
spec:
  vaultRef:
    name: vault
  databaseRef:
    name: mongodb
    namespace: demo
  path: "your-database-path"
  creationStatements:
    - "{ \"db\": \"admin\", \"roles\": [{ \"role\": \"readWrite\" }, {\"role\": \"read\", \"db\": \"foo\"}] }"
  defaultTTL: 1h
  maxTTL: 24h