apiVersion: engine.kubevault.com/v1alpha1
kind: MongoDBRole
metadata:
  name: mongo-superuser-role
  namespace: demo
spec:
  secretEngineRef:
    name: mongo-secret-engine
  creationStatements:
    - "{ \"db\": \"admin\", \"roles\": [{ \"role\": \"readWrite\" }, {\"role\": \"read\", \"db\": \"foo\"}] }"
  defaultTTL: 1h
  maxTTL: 24h