apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: es-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  elasticsearch:
    databaseRef:
      name: elasticsearch
      namespace: demo
    pluginName: "elasticsearch-database-plugin"
