apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-db-provider
  namespace: demo
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.demo:8200"
    roleName: "k8s.-.demo.es-reader-role"
    objects: |
      - objectName: "es-creds-username"
        secretPath: "your-database-path/creds/k8s.-.demo.es-superuser-role"
        secretKey: "username"
      - objectName: "es-creds-password"
        secretPath: "your-database-path/creds/k8s.-.demo.es-superuser-role"
        secretKey: "password"