apiVersion: engine.kubevault.com/v1alpha1
kind: ElasticsearchRole
metadata:
  name: es-superuser-role
  namespace: demo
spec:
  vaultRef:
    name: vault
  databaseRef:
    name: elasticsearch
    namespace: demo
  path: "your-database-path"
  creationStatements:
    - '{"elasticsearch_roles": ["superuser"]}'
  defaultTTL: 1h
  maxTTL: 24h
