/*
Copyright The KubeVault Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kubevault.dev/operator/apis/approle/v1alpha1/generated.proto

package v1alpha1

import (
	fmt "fmt"

	io "io"

	proto "github.com/gogo/protobuf/proto"

	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"

	v12 "kmodules.xyz/client-go/api/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

func (m *VaultAppRole) Reset()      { *m = VaultAppRole{} }
func (*VaultAppRole) ProtoMessage() {}
func (*VaultAppRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_b09a2e6a72ec50b5, []int{0}
}
func (m *VaultAppRole) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VaultAppRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *VaultAppRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VaultAppRole.Merge(m, src)
}
func (m *VaultAppRole) XXX_Size() int {
	return m.Size()
}
func (m *VaultAppRole) XXX_DiscardUnknown() {
	xxx_messageInfo_VaultAppRole.DiscardUnknown(m)
}

var xxx_messageInfo_VaultAppRole proto.InternalMessageInfo

func (m *VaultAppRoleList) Reset()      { *m = VaultAppRoleList{} }
func (*VaultAppRoleList) ProtoMessage() {}
func (*VaultAppRoleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b09a2e6a72ec50b5, []int{1}
}
func (m *VaultAppRoleList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VaultAppRoleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *VaultAppRoleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VaultAppRoleList.Merge(m, src)
}
func (m *VaultAppRoleList) XXX_Size() int {
	return m.Size()
}
func (m *VaultAppRoleList) XXX_DiscardUnknown() {
	xxx_messageInfo_VaultAppRoleList.DiscardUnknown(m)
}

var xxx_messageInfo_VaultAppRoleList proto.InternalMessageInfo

func (m *VaultAppRoleSpec) Reset()      { *m = VaultAppRoleSpec{} }
func (*VaultAppRoleSpec) ProtoMessage() {}
func (*VaultAppRoleSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_b09a2e6a72ec50b5, []int{2}
}
func (m *VaultAppRoleSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VaultAppRoleSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *VaultAppRoleSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VaultAppRoleSpec.Merge(m, src)
}
func (m *VaultAppRoleSpec) XXX_Size() int {
	return m.Size()
}
func (m *VaultAppRoleSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_VaultAppRoleSpec.DiscardUnknown(m)
}

var xxx_messageInfo_VaultAppRoleSpec proto.InternalMessageInfo

func (m *VaultAppRoleStatus) Reset()      { *m = VaultAppRoleStatus{} }
func (*VaultAppRoleStatus) ProtoMessage() {}
func (*VaultAppRoleStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_b09a2e6a72ec50b5, []int{3}
}
func (m *VaultAppRoleStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VaultAppRoleStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *VaultAppRoleStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VaultAppRoleStatus.Merge(m, src)
}
func (m *VaultAppRoleStatus) XXX_Size() int {
	return m.Size()
}
func (m *VaultAppRoleStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_VaultAppRoleStatus.DiscardUnknown(m)
}

var xxx_messageInfo_VaultAppRoleStatus proto.InternalMessageInfo

func init() {
	proto.RegisterType((*VaultAppRole)(nil), "kubevault.dev.operator.apis.approle.v1alpha1.VaultAppRole")
	proto.RegisterType((*VaultAppRoleList)(nil), "kubevault.dev.operator.apis.approle.v1alpha1.VaultAppRoleList")
	proto.RegisterType((*VaultAppRoleSpec)(nil), "kubevault.dev.operator.apis.approle.v1alpha1.VaultAppRoleSpec")
	proto.RegisterType((*VaultAppRoleStatus)(nil), "kubevault.dev.operator.apis.approle.v1alpha1.VaultAppRoleStatus")
}

func init() {
	proto.RegisterFile("kubevault.dev/operator/apis/approle/v1alpha1/generated.proto", fileDescriptor_b09a2e6a72ec50b5)
}

var fileDescriptor_b09a2e6a72ec50b5 = []byte{
	// 1010 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0x35, 0x2d, 0xdb, 0x95, 0x46, 0xf2, 0x6b, 0xec, 0x26, 0x84, 0x5b, 0xc8, 0x86, 0x57, 0x5a,
	0xd4, 0xc3, 0xd8, 0x28, 0x92, 0x20, 0x28, 0xfa, 0x60, 0x1c, 0x14, 0x2e, 0x12, 0xc7, 0x18, 0xbb,
	0x5e, 0x14, 0x01, 0x94, 0x11, 0x79, 0x2d, 0xb1, 0x22, 0x39, 0x04, 0x67, 0x28, 0x58, 0x5d, 0xf5,
	0x13, 0xfa, 0x11, 0xfd, 0x8c, 0x7e, 0x80, 0x97, 0xe9, 0x2e, 0x2b, 0xa3, 0x56, 0xff, 0xa0, 0xcb,
	0xae, 0x8a, 0x79, 0x50, 0x92, 0x23, 0x17, 0x7d, 0x64, 0xc7, 0x7b, 0xe7, 0x9e, 0x73, 0xcf, 0x7d,
	0x70, 0x06, 0x7d, 0xd6, 0x2f, 0x3a, 0x30, 0x60, 0x45, 0x2c, 0x49, 0x08, 0x03, 0x8f, 0x67, 0x90,
	0x33, 0xc9, 0x73, 0x8f, 0x65, 0x91, 0xf0, 0x58, 0x96, 0xe5, 0x3c, 0x06, 0x6f, 0xb0, 0xcf, 0xe2,
	0xac, 0xc7, 0xf6, 0xbd, 0x2e, 0xa4, 0xea, 0x1c, 0x42, 0x92, 0xe5, 0x5c, 0x72, 0xfc, 0xc9, 0x2d,
	0x34, 0x29, 0xd1, 0x44, 0xa1, 0x89, 0x45, 0x93, 0x12, 0xbd, 0xb5, 0xd7, 0x8d, 0x64, 0xaf, 0xe8,
	0x90, 0x80, 0x27, 0x5e, 0x97, 0x77, 0xb9, 0xa7, 0x49, 0x3a, 0xc5, 0x85, 0xb6, 0xb4, 0xa1, 0xbf,
	0x0c, 0xf9, 0xd6, 0x6e, 0xff, 0xb1, 0x20, 0x11, 0x57, 0x52, 0xbc, 0x80, 0xe7, 0x4a, 0xc6, 0xbb,
	0x02, 0xb6, 0x3e, 0x9d, 0xc4, 0x24, 0x2c, 0xe8, 0x45, 0x29, 0xe4, 0x43, 0x2f, 0xeb, 0x77, 0x8d,
	0xfe, 0x04, 0x24, 0xbb, 0x0b, 0xe5, 0xfd, 0x1d, 0x2a, 0x2f, 0x52, 0x19, 0x25, 0x30, 0x03, 0x78,
	0xf8, 0x4f, 0x00, 0x11, 0xf4, 0x20, 0x61, 0x33, 0xb8, 0xbd, 0x7e, 0xc2, 0xc3, 0x22, 0x06, 0x41,
	0x2e, 0x87, 0x3f, 0x78, 0x41, 0x1c, 0x41, 0x2a, 0xf7, 0xba, 0xa6, 0xa4, 0x59, 0x5d, 0xbb, 0xbf,
	0xcc, 0xa3, 0xc6, 0xb9, 0xea, 0xe6, 0x57, 0x59, 0x46, 0x79, 0x0c, 0xf8, 0x35, 0xaa, 0xaa, 0x1a,
	0x42, 0x26, 0x99, 0xeb, 0xec, 0x38, 0xad, 0xfa, 0xc1, 0x03, 0x62, 0xa4, 0x90, 0x69, 0x29, 0x24,
	0xeb, 0x77, 0x4d, 0xcf, 0x55, 0x34, 0x19, 0xec, 0x93, 0x97, 0x9d, 0xef, 0x21, 0x90, 0x2f, 0x40,
	0x32, 0x1f, 0x5f, 0x5d, 0x6f, 0xcf, 0x8d, 0xae, 0xb7, 0xd1, 0xc4, 0x47, 0xc7, 0xac, 0xf8, 0x35,
	0x5a, 0x10, 0x19, 0x04, 0xee, 0xbc, 0x66, 0xff, 0x9c, 0xfc, 0x97, 0x81, 0x92, 0x69, 0xad, 0xa7,
	0x19, 0x04, 0x7e, 0xc3, 0xe6, 0x5a, 0x50, 0x16, 0xd5, 0xcc, 0xb8, 0x87, 0x96, 0x84, 0x64, 0xb2,
	0x10, 0x6e, 0x45, 0xe7, 0xf8, 0xf2, 0x3d, 0x72, 0x68, 0x1e, 0x7f, 0xc5, 0x66, 0x59, 0x32, 0x36,
	0xb5, 0xfc, 0xbb, 0xbf, 0x3a, 0x68, 0x6d, 0x3a, 0xfc, 0x79, 0x24, 0x24, 0x7e, 0x35, 0xd3, 0x42,
	0xf2, 0xef, 0x5a, 0xa8, 0xd0, 0xba, 0x81, 0x6b, 0x36, 0x5d, 0xb5, 0xf4, 0x4c, 0xb5, 0xaf, 0x8d,
	0x16, 0x23, 0x09, 0x89, 0x70, 0xe7, 0x77, 0x2a, 0xad, 0xfa, 0xc1, 0x93, 0xff, 0x5f, 0x9b, 0xbf,
	0x6c, 0xd3, 0x2c, 0x1e, 0x29, 0x42, 0x6a, 0x78, 0x77, 0x7f, 0xae, 0xde, 0xae, 0x49, 0x35, 0x16,
	0x9f, 0xa3, 0xaa, 0xce, 0x41, 0xe1, 0xc2, 0xd6, 0xd4, 0x9a, 0xaa, 0x89, 0xa8, 0x9f, 0x45, 0x57,
	0xc0, 0x03, 0x16, 0x9b, 0xa9, 0x53, 0xb8, 0x80, 0x1c, 0xd2, 0x00, 0x26, 0xd5, 0x9c, 0x5b, 0x06,
	0x3a, 0xe6, 0xc2, 0x7b, 0xa8, 0xa6, 0x04, 0xb6, 0x53, 0x96, 0x80, 0xde, 0x88, 0xda, 0x24, 0x5c,
	0x25, 0x3f, 0x66, 0x09, 0xd0, 0x6a, 0x6e, 0xbf, 0xf0, 0x13, 0xb4, 0xd2, 0x89, 0xd2, 0xb0, 0x2d,
	0x20, 0xc8, 0x41, 0xb6, 0xa3, 0x50, 0x4f, 0xb8, 0xe6, 0x6f, 0x5a, 0x4c, 0xc3, 0x8f, 0xd2, 0xf0,
	0x54, 0x1f, 0x1e, 0x1d, 0xd2, 0x46, 0x67, 0x62, 0x85, 0xf8, 0x08, 0x7d, 0x38, 0x86, 0xb5, 0x3b,
	0xbc, 0x48, 0xc3, 0x76, 0x10, 0x85, 0xb9, 0x70, 0x17, 0x76, 0x2a, 0xad, 0x9a, 0x7f, 0x6f, 0x74,
	0xbd, 0x8d, 0x4b, 0xa8, 0xaf, 0x8e, 0x9f, 0xaa, 0x53, 0x8a, 0x85, 0x25, 0x98, 0xf8, 0xf0, 0x21,
	0xc2, 0x13, 0xaa, 0xb4, 0x48, 0xda, 0x85, 0x00, 0xe1, 0x2e, 0xee, 0x38, 0xad, 0x8a, 0x7f, 0xdf,
	0x4a, 0x59, 0x2d, 0xb9, 0x8e, 0x8b, 0xe4, 0x5b, 0x01, 0x82, 0xae, 0x96, 0x44, 0xd6, 0x81, 0x1f,
	0xa1, 0xe5, 0x09, 0x8b, 0x94, 0xb1, 0xbb, 0xa4, 0x6b, 0xd9, 0xb0, 0x04, 0xf5, 0x92, 0xe0, 0xec,
	0xec, 0x39, 0xad, 0x97, 0xe0, 0x33, 0x19, 0xe3, 0x53, 0x74, 0x1f, 0x52, 0xd6, 0x89, 0xa1, 0x1d,
	0xab, 0x7e, 0x4f, 0xba, 0x21, 0xdc, 0x0f, 0x76, 0x9c, 0x56, 0xd5, 0xff, 0xd8, 0x52, 0x6c, 0x3e,
	0xd3, 0x61, 0x7a, 0x2a, 0x25, 0x9b, 0xa0, 0x9b, 0x30, 0xe3, 0x0d, 0x85, 0x9a, 0x84, 0xe4, 0x7d,
	0x48, 0xb5, 0x92, 0xaa, 0x2e, 0x65, 0x3c, 0x89, 0x33, 0x75, 0xa0, 0x64, 0x54, 0x75, 0x88, 0xd2,
	0xf0, 0x08, 0x2d, 0x9b, 0xf0, 0x84, 0x5d, 0x6a, 0x48, 0x4d, 0x43, 0xc6, 0xe2, 0x35, 0xe4, 0x05,
	0xbb, 0xd4, 0xe2, 0x65, 0x69, 0xc8, 0x18, 0x3f, 0x46, 0x2b, 0x06, 0x98, 0xf1, 0x38, 0x0a, 0x22,
	0x10, 0x2e, 0xd2, 0xfd, 0x5f, 0x1f, 0x5d, 0x6f, 0x2f, 0x6b, 0xd4, 0x89, 0x3d, 0xa0, 0x26, 0x43,
	0x69, 0xe2, 0x2f, 0xd0, 0xba, 0x41, 0x4e, 0x0f, 0xaf, 0xae, 0xc1, 0x1b, 0xaa, 0xe1, 0x1a, 0x3c,
	0x35, 0xb9, 0x55, 0x79, 0xdb, 0x81, 0x4f, 0xd0, 0x3d, 0x43, 0x00, 0x97, 0x99, 0xe2, 0x94, 0x63,
	0xf1, 0x0d, 0x2d, 0xfe, 0x23, 0x2b, 0x7e, 0x43, 0x33, 0x3d, 0xb3, 0x41, 0xb6, 0x88, 0x0d, 0xf9,
	0xae, 0xd3, 0x4c, 0xc2, 0x30, 0xa6, 0xbc, 0x1d, 0xc2, 0x85, 0xda, 0x6a, 0x53, 0xd7, 0xd0, 0x5d,
	0xbe, 0x3d, 0x09, 0x4d, 0x79, 0xcc, 0x0f, 0x4d, 0x90, 0xae, 0x69, 0x48, 0x37, 0xe5, 0x1d, 0x5e,
	0xb5, 0xe4, 0x96, 0xb4, 0xdc, 0xac, 0x15, 0x2d, 0x6f, 0xbc, 0xe4, 0x86, 0xcb, 0xae, 0x55, 0x43,
	0x4e, 0x59, 0xf8, 0x21, 0x6a, 0xd8, 0xee, 0x42, 0x1e, 0xf1, 0xd0, 0x5d, 0xbd, 0x63, 0x2a, 0x27,
	0xfa, 0xc8, 0x4e, 0xc5, 0x18, 0xf8, 0x01, 0x42, 0x76, 0xfa, 0xc3, 0x0c, 0xdc, 0x35, 0xbd, 0x88,
	0xeb, 0x16, 0x55, 0x33, 0xe3, 0x1f, 0x66, 0x40, 0xcd, 0x8a, 0xa8, 0xcf, 0xdd, 0x3f, 0x1c, 0x84,
	0x67, 0x6f, 0x4a, 0xfc, 0x0d, 0xc2, 0xbc, 0x23, 0x20, 0x1f, 0x40, 0xf8, 0xb5, 0x79, 0x6b, 0x22,
	0x9e, 0xea, 0x2b, 0xa3, 0xe2, 0x6f, 0x59, 0x42, 0xfc, 0x72, 0x26, 0x82, 0xde, 0x81, 0xc2, 0x07,
	0x68, 0x31, 0xeb, 0x31, 0x51, 0x5e, 0x0c, 0x65, 0x2f, 0x17, 0x4f, 0x94, 0xf3, 0xcf, 0xeb, 0xed,
	0xba, 0x69, 0x98, 0x36, 0xa9, 0x09, 0xc5, 0xaf, 0x10, 0x0a, 0x78, 0x1a, 0x46, 0x8a, 0x40, 0xdd,
	0xff, 0x15, 0x73, 0x55, 0x4d, 0x3d, 0x8a, 0xc4, 0x3c, 0x8a, 0xed, 0xae, 0xb9, 0xba, 0x06, 0xfb,
	0xe4, 0x69, 0x09, 0x98, 0xbc, 0x5c, 0x63, 0x97, 0xa0, 0x53, 0x7c, 0x3e, 0xb9, 0xba, 0x69, 0xce,
	0xbd, 0xb9, 0x69, 0xce, 0xbd, 0xbd, 0x69, 0xce, 0xfd, 0x38, 0x6a, 0x3a, 0x57, 0xa3, 0xa6, 0xf3,
	0x66, 0xd4, 0x74, 0xde, 0x8e, 0x9a, 0xce, 0x6f, 0xa3, 0xa6, 0xf3, 0xd3, 0xef, 0xcd, 0xb9, 0xef,
	0xaa, 0xe5, 0x75, 0xfb, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x95, 0x21, 0x61, 0xd3, 0xec, 0x08,
	0x00, 0x00,
}

func (m *VaultAppRole) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VaultAppRole) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VaultAppRole) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *VaultAppRoleList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VaultAppRoleList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VaultAppRoleList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *VaultAppRoleSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VaultAppRoleSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VaultAppRoleSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.TokenType)
	copy(dAtA[i:], m.TokenType)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.TokenType)))
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x82
	i = encodeVarintGenerated(dAtA, i, uint64(m.TokenPeriod))
	i--
	dAtA[i] = 0x78
	i = encodeVarintGenerated(dAtA, i, uint64(m.TokenNumUses))
	i--
	dAtA[i] = 0x70
	i--
	if m.TokenNoDefaultPolicy {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x68
	i = encodeVarintGenerated(dAtA, i, uint64(m.TokenExplicitMaxTTL))
	i--
	dAtA[i] = 0x60
	if len(m.TokenBoundCidrs) > 0 {
		for iNdEx := len(m.TokenBoundCidrs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TokenBoundCidrs[iNdEx])
			copy(dAtA[i:], m.TokenBoundCidrs[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(m.TokenBoundCidrs[iNdEx])))
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.TokenPolicies) > 0 {
		for iNdEx := len(m.TokenPolicies) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TokenPolicies[iNdEx])
			copy(dAtA[i:], m.TokenPolicies[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(m.TokenPolicies[iNdEx])))
			i--
			dAtA[i] = 0x52
		}
	}
	i = encodeVarintGenerated(dAtA, i, uint64(m.TokenMaxTTL))
	i--
	dAtA[i] = 0x48
	i = encodeVarintGenerated(dAtA, i, uint64(m.TokenTTL))
	i--
	dAtA[i] = 0x40
	i--
	if m.EnableLocalSecretIDs {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x38
	i -= len(m.SecretIDTTL)
	copy(dAtA[i:], m.SecretIDTTL)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.SecretIDTTL)))
	i--
	dAtA[i] = 0x32
	i = encodeVarintGenerated(dAtA, i, uint64(m.SecretIDNumUses))
	i--
	dAtA[i] = 0x28
	if len(m.SecretIDBoundCidrs) > 0 {
		for iNdEx := len(m.SecretIDBoundCidrs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SecretIDBoundCidrs[iNdEx])
			copy(dAtA[i:], m.SecretIDBoundCidrs[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(m.SecretIDBoundCidrs[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	i -= len(m.BindSecretID)
	copy(dAtA[i:], m.BindSecretID)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.BindSecretID)))
	i--
	dAtA[i] = 0x1a
	i -= len(m.RoleName)
	copy(dAtA[i:], m.RoleName)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.RoleName)))
	i--
	dAtA[i] = 0x12
	{
		size, err := m.VaultRef.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *VaultAppRoleStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VaultAppRoleStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VaultAppRoleStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Conditions) > 0 {
		for iNdEx := len(m.Conditions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Conditions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	i -= len(m.Phase)
	copy(dAtA[i:], m.Phase)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Phase)))
	i--
	dAtA[i] = 0x12
	i = encodeVarintGenerated(dAtA, i, uint64(m.ObservedGeneration))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VaultAppRole) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *VaultAppRoleList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *VaultAppRoleSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.VaultRef.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.RoleName)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.BindSecretID)
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.SecretIDBoundCidrs) > 0 {
		for _, s := range m.SecretIDBoundCidrs {
			l = len(s)
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	n += 1 + sovGenerated(uint64(m.SecretIDNumUses))
	l = len(m.SecretIDTTL)
	n += 1 + l + sovGenerated(uint64(l))
	n += 2
	n += 1 + sovGenerated(uint64(m.TokenTTL))
	n += 1 + sovGenerated(uint64(m.TokenMaxTTL))
	if len(m.TokenPolicies) > 0 {
		for _, s := range m.TokenPolicies {
			l = len(s)
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if len(m.TokenBoundCidrs) > 0 {
		for _, s := range m.TokenBoundCidrs {
			l = len(s)
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	n += 1 + sovGenerated(uint64(m.TokenExplicitMaxTTL))
	n += 2
	n += 1 + sovGenerated(uint64(m.TokenNumUses))
	n += 1 + sovGenerated(uint64(m.TokenPeriod))
	l = len(m.TokenType)
	n += 2 + l + sovGenerated(uint64(l))
	return n
}

func (m *VaultAppRoleStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovGenerated(uint64(m.ObservedGeneration))
	l = len(m.Phase)
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Conditions) > 0 {
		for _, e := range m.Conditions {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *VaultAppRole) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&VaultAppRole{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "VaultAppRoleSpec", "VaultAppRoleSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "VaultAppRoleStatus", "VaultAppRoleStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *VaultAppRoleList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]VaultAppRole{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "VaultAppRole", "VaultAppRole", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&VaultAppRoleList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *VaultAppRoleSpec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&VaultAppRoleSpec{`,
		`VaultRef:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.VaultRef), "LocalObjectReference", "v11.LocalObjectReference", 1), `&`, ``, 1) + `,`,
		`RoleName:` + fmt.Sprintf("%v", this.RoleName) + `,`,
		`BindSecretID:` + fmt.Sprintf("%v", this.BindSecretID) + `,`,
		`SecretIDBoundCidrs:` + fmt.Sprintf("%v", this.SecretIDBoundCidrs) + `,`,
		`SecretIDNumUses:` + fmt.Sprintf("%v", this.SecretIDNumUses) + `,`,
		`SecretIDTTL:` + fmt.Sprintf("%v", this.SecretIDTTL) + `,`,
		`EnableLocalSecretIDs:` + fmt.Sprintf("%v", this.EnableLocalSecretIDs) + `,`,
		`TokenTTL:` + fmt.Sprintf("%v", this.TokenTTL) + `,`,
		`TokenMaxTTL:` + fmt.Sprintf("%v", this.TokenMaxTTL) + `,`,
		`TokenPolicies:` + fmt.Sprintf("%v", this.TokenPolicies) + `,`,
		`TokenBoundCidrs:` + fmt.Sprintf("%v", this.TokenBoundCidrs) + `,`,
		`TokenExplicitMaxTTL:` + fmt.Sprintf("%v", this.TokenExplicitMaxTTL) + `,`,
		`TokenNoDefaultPolicy:` + fmt.Sprintf("%v", this.TokenNoDefaultPolicy) + `,`,
		`TokenNumUses:` + fmt.Sprintf("%v", this.TokenNumUses) + `,`,
		`TokenPeriod:` + fmt.Sprintf("%v", this.TokenPeriod) + `,`,
		`TokenType:` + fmt.Sprintf("%v", this.TokenType) + `,`,
		`}`,
	}, "")
	return s
}
func (this *VaultAppRoleStatus) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForConditions := "[]Condition{"
	for _, f := range this.Conditions {
		repeatedStringForConditions += fmt.Sprintf("%v", f) + ","
	}
	repeatedStringForConditions += "}"
	s := strings.Join([]string{`&VaultAppRoleStatus{`,
		`ObservedGeneration:` + fmt.Sprintf("%v", this.ObservedGeneration) + `,`,
		`Phase:` + fmt.Sprintf("%v", this.Phase) + `,`,
		`Conditions:` + repeatedStringForConditions + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *VaultAppRole) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VaultAppRole: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VaultAppRole: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VaultAppRoleList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VaultAppRoleList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VaultAppRoleList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, VaultAppRole{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VaultAppRoleSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VaultAppRoleSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VaultAppRoleSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VaultRef", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VaultRef.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoleName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoleName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BindSecretID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BindSecretID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretIDBoundCidrs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecretIDBoundCidrs = append(m.SecretIDBoundCidrs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretIDNumUses", wireType)
			}
			m.SecretIDNumUses = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SecretIDNumUses |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretIDTTL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecretIDTTL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnableLocalSecretIDs", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnableLocalSecretIDs = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenTTL", wireType)
			}
			m.TokenTTL = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenTTL |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenMaxTTL", wireType)
			}
			m.TokenMaxTTL = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenMaxTTL |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenPolicies", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenPolicies = append(m.TokenPolicies, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenBoundCidrs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenBoundCidrs = append(m.TokenBoundCidrs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenExplicitMaxTTL", wireType)
			}
			m.TokenExplicitMaxTTL = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenExplicitMaxTTL |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenNoDefaultPolicy", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TokenNoDefaultPolicy = bool(v != 0)
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenNumUses", wireType)
			}
			m.TokenNumUses = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenNumUses |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenPeriod", wireType)
			}
			m.TokenPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenPeriod |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VaultAppRoleStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VaultAppRoleStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VaultAppRoleStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedGeneration", wireType)
			}
			m.ObservedGeneration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObservedGeneration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phase", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Phase = PolicyPhase(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Conditions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Conditions = append(m.Conditions, v12.Condition{})
			if err := m.Conditions[len(m.Conditions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGenerated(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthGenerated
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGenerated = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated   = fmt.Errorf("proto: integer overflow")
)
