apiVersion: engine.kubevault.com/v1alpha1
kind: MemcachedRole
metadata:
  name: memcached-app-role
  namespace: demo
spec:
  secretEngineRef:
    name: memcached-engine
  defaultTTL: 24h
  maxTTL: 168h
