apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: memcached-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  memcached:
    databaseRef:
      name: memcached
      namespace: demo
    pluginName: memcached-database-plugin
    allowedRoles:
    - "*"
