apiVersion: engine.kubevault.com/v1alpha1
kind: SolrRole
metadata:
  name: solr-superuser-role
  namespace: demo
spec:
  secretEngineRef:
    name: solr-engine
  creationStatements:
    - '{"roles":["admin","read"]}'
  defaultTTL: 1h
  maxTTL: 24h
