apiVersion: engine.kubevault.com/v1alpha1
kind: RabbitMQRole
metadata:
  name: rabbitmq-superuser-role
  namespace: demo
spec:
  secretEngineRef:
    name: rabbitmq-engine
  creationStatements:
    - '{"tags":"administrator","vhosts":{"/":{"configure":".*","write":".*","read":".*"}}}'
  defaultTTL: 1h
  maxTTL: 24h
