apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicy
metadata:
  name: pki-se-policy
  namespace: demo
spec:
  vaultRef:
    name: vault
  policyDocument: |
    path "pki/issue/*" {
      capabilities = ["update"]
    }
