apiVersion: engine.kubevault.com/v1alpha1
kind: GCPRole
metadata:
  name: gcp-role
  namespace: demo
spec:
  vaultRef:
    name: vault
  secretType: access_token
  project: ackube
  bindings: |
    resource "//cloudresourcemanager.googleapis.com/projects/ackube" {
      roles = ["roles/viewer"]
    }
  tokenScopes: ["https://www.googleapis.com/auth/cloud-platform"]