apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-db-provider
  namespace: demo
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.demo:8200"
    roleName: k8s.kubevault.com.demo.srb-demo-secret-role-binding
    objects: |
      - objectName: "redis-creds-username"
        secretPath: "/k8s.kubevault.com.redis.demo.redis-secret-engine/creds/k8s.kubevault.com.demo.write-read-role"
       #secretPath: "your-database-path/creds/your-role-name" 
        secretKey: "username"
      - objectName: "redis-creds-password"
        secretPath: "/k8s.kubevault.com.redis.demo.redis-secret-engine/creds/k8s.kubevault.com.demo.write-read-role"
       #secretPath: "your-database-path/creds/your-role-name"
        secretKey: "password"