/*
Copyright 2019 The Kube Vault Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AWSAccessKeyRequestListerExpansion allows custom methods to be added to
// AWSAccessKeyRequestLister.
type AWSAccessKeyRequestListerExpansion interface{}

// AWSAccessKeyRequestNamespaceListerExpansion allows custom methods to be added to
// AWSAccessKeyRequestNamespaceLister.
type AWSAccessKeyRequestNamespaceListerExpansion interface{}

// AWSRoleListerExpansion allows custom methods to be added to
// AWSRoleLister.
type AWSRoleListerExpansion interface{}

// AWSRoleNamespaceListerExpansion allows custom methods to be added to
// AWSRoleNamespaceLister.
type AWSRoleNamespaceListerExpansion interface{}

// AzureRoleListerExpansion allows custom methods to be added to
// AzureRoleLister.
type AzureRoleListerExpansion interface{}

// AzureRoleNamespaceListerExpansion allows custom methods to be added to
// AzureRoleNamespaceLister.
type AzureRoleNamespaceListerExpansion interface{}

// GCPAccessKeyRequestListerExpansion allows custom methods to be added to
// GCPAccessKeyRequestLister.
type GCPAccessKeyRequestListerExpansion interface{}

// GCPAccessKeyRequestNamespaceListerExpansion allows custom methods to be added to
// GCPAccessKeyRequestNamespaceLister.
type GCPAccessKeyRequestNamespaceListerExpansion interface{}

// GCPRoleListerExpansion allows custom methods to be added to
// GCPRoleLister.
type GCPRoleListerExpansion interface{}

// GCPRoleNamespaceListerExpansion allows custom methods to be added to
// GCPRoleNamespaceLister.
type GCPRoleNamespaceListerExpansion interface{}
