apiVersion: engine.kubevault.com/v1alpha1
kind: Neo4jRole
metadata:
  name: neo4j-superuser-role
  namespace: demo
spec:
  secretEngineRef:
    name: neo4j-engine
  creationStatements:
    - '{"roles":["admin"]}'
  defaultTTL: 1h
  maxTTL: 24h
