apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: neo4j-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  neo4j:
    databaseRef:
      name: neo4j
      namespace: demo
    pluginName: neo4j-database-plugin
    allowedRoles:
      - "*"
    insecure: false
