apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: etcd-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  etcd:
    databaseRef:
      name: etcd
      namespace: demo
    pluginName: etcd-database-plugin
    allowedRoles:
      - "*"
