/*
Copyright The KubeVault Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubevault.dev/operator/apis/approle/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVaultAppRoles implements VaultAppRoleInterface
type FakeVaultAppRoles struct {
	Fake *FakeApproleV1alpha1
	ns   string
}

var vaultapprolesResource = schema.GroupVersionResource{Group: "approle.kubevault.com", Version: "v1alpha1", Resource: "vaultapproles"}

var vaultapprolesKind = schema.GroupVersionKind{Group: "approle.kubevault.com", Version: "v1alpha1", Kind: "VaultAppRole"}

// Get takes name of the vaultAppRole, and returns the corresponding vaultAppRole object, and an error if there is any.
func (c *FakeVaultAppRoles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VaultAppRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vaultapprolesResource, c.ns, name), &v1alpha1.VaultAppRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultAppRole), err
}

// List takes label and field selectors, and returns the list of VaultAppRoles that match those selectors.
func (c *FakeVaultAppRoles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VaultAppRoleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vaultapprolesResource, vaultapprolesKind, c.ns, opts), &v1alpha1.VaultAppRoleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VaultAppRoleList{ListMeta: obj.(*v1alpha1.VaultAppRoleList).ListMeta}
	for _, item := range obj.(*v1alpha1.VaultAppRoleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vaultAppRoles.
func (c *FakeVaultAppRoles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vaultapprolesResource, c.ns, opts))

}

// Create takes the representation of a vaultAppRole and creates it.  Returns the server's representation of the vaultAppRole, and an error, if there is any.
func (c *FakeVaultAppRoles) Create(ctx context.Context, vaultAppRole *v1alpha1.VaultAppRole, opts v1.CreateOptions) (result *v1alpha1.VaultAppRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vaultapprolesResource, c.ns, vaultAppRole), &v1alpha1.VaultAppRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultAppRole), err
}

// Update takes the representation of a vaultAppRole and updates it. Returns the server's representation of the vaultAppRole, and an error, if there is any.
func (c *FakeVaultAppRoles) Update(ctx context.Context, vaultAppRole *v1alpha1.VaultAppRole, opts v1.UpdateOptions) (result *v1alpha1.VaultAppRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vaultapprolesResource, c.ns, vaultAppRole), &v1alpha1.VaultAppRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultAppRole), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVaultAppRoles) UpdateStatus(ctx context.Context, vaultAppRole *v1alpha1.VaultAppRole, opts v1.UpdateOptions) (*v1alpha1.VaultAppRole, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(vaultapprolesResource, "status", c.ns, vaultAppRole), &v1alpha1.VaultAppRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultAppRole), err
}

// Delete takes name of the vaultAppRole and deletes it. Returns an error if one occurs.
func (c *FakeVaultAppRoles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(vaultapprolesResource, c.ns, name), &v1alpha1.VaultAppRole{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVaultAppRoles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vaultapprolesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VaultAppRoleList{})
	return err
}

// Patch applies the patch and returns the patched vaultAppRole.
func (c *FakeVaultAppRoles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VaultAppRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vaultapprolesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VaultAppRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultAppRole), err
}
