apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubevault
  name: vaultapproles.approle.kubevault.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: approle.kubevault.com
  names:
    categories:
    - vault
    - approle
    - appscode
    - all
    kind: VaultAppRole
    listKind: VaultAppRoleList
    plural: vaultapproles
    shortNames:
    - vp
    singular: vaultapprole
  preserveUnknownFields: false
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: 'More info: https://www.vaultproject.io/api-docs/auth/approle'
          properties:
            bindSecretID:
              description: Require secret_id to be presented when logging in using
                this AppRole.
              type: boolean
            enableLocalSecretIds:
              description: If set, the secret IDs generated using this role will be
                cluster local. This can only be set during role creation and once
                set, it can't be reset later.
              type: boolean
            roleName:
              description: 'RoleName is the Name of the AppRole This defaults to following
                format: k8s.${cluster}.${metadata.namespace}.${metadata.name}'
              type: string
            secretIdBoundCidrs:
              description: List of CIDR blocks; if set, specifies blocks of IP addresses
                which can perform the login operation.
              items:
                type: string
              type: array
            secretIdNumUses:
              description: Number of times any particular SecretID can be used to
                fetch a token from this AppRole, after which the SecretID will expire.
                A value of zero will allow unlimited uses.
              format: int64
              type: integer
            secretIdTTL:
              description: Duration in either an integer number of seconds (3600)
                or an integer time unit (60m) after which any SecretID expires.
              type: string
            tokenBoundCidrs:
              description: List of CIDR blocks; if set, specifies blocks of IP addresses
                which can authenticate successfully, and ties the resulting token
                to these blocks as well.
              items:
                type: string
              type: array
            tokenExplicitMaxTTL:
              description: If set, will encode an explicit max TTL onto the token.
                This is a hard cap even if token_ttl and token_max_ttl would otherwise
                allow a renewal.
              format: int64
              type: integer
            tokenMaxTTL:
              description: The maximum lifetime for generated tokens. This current
                value of this will be referenced at renewal time.
              format: int64
              type: integer
            tokenNoDefaultPolicy:
              description: If set, the default policy will not be set on generated
                tokens; otherwise it will be added to the policies set in token_policies.
              type: boolean
            tokenNumUses:
              description: The maximum number of times a generated token may be used
                (within its lifetime); 0 means unlimited.
              format: int64
              type: integer
            tokenPeriod:
              description: The period, if any, to set on the token.
              format: int64
              type: integer
            tokenPolicies:
              description: List of policies to encode onto generated tokens. Depending
                on the auth method, this list may be supplemented by user/group/other
                values.
              items:
                type: string
              type: array
            tokenTTL:
              description: The incremental lifetime for generated tokens. This current
                value of this will be referenced at renewal time.
              format: int64
              type: integer
            tokenType:
              description: 'The type of token that should be generated. Can be service,
                batch, or default to use the mount''s tuned default (which unless
                changed will be service tokens). For token store roles, there are
                two additional possibilities: default-service and default-batch which
                specify the type to return unless the client requests a different
                type at generation time.'
              type: string
            vaultRef:
              description: VaultRef is the name of a AppBinding referencing to a Vault
                Server
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
          required:
          - bindSecretID
          - vaultRef
          type: object
        status:
          properties:
            conditions:
              description: Represents the latest available observations of a VaultPolicy.
              items:
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another. This should be when the underlying condition changed.  If
                      that is not known, then using the time when the API field changed
                      is acceptable.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition. This field may be empty.
                    type: string
                  observedGeneration:
                    description: If set, this represents the .metadata.generation
                      that the condition was set based upon. For instance, if .metadata.generation
                      is currently 12, but the .status.condition[x].observedGeneration
                      is 9, the condition is out of date with respect to the current
                      state of the instance.
                    format: int64
                    type: integer
                  reason:
                    description: The reason for the condition's last transition in
                      CamelCase. The specific API may choose whether or not this field
                      is considered a guaranteed API. This field may not be empty.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                      Many .condition.type values are consistent across resources
                      like Available, but because arbitrary conditions can be useful
                      (see .node.status.conditions), the ability to deconflict is
                      important.
                    type: string
                required:
                - lastTransitionTime
                - message
                - reason
                - status
                - type
                type: object
              type: array
            observedGeneration:
              description: ObservedGeneration is the most recent generation observed
                for this resource. It corresponds to the resource's generation, which
                is updated on mutation by the API Server.
              format: int64
              type: integer
            phase:
              description: Phase indicates whether the policy successfully applied
                in vault or not or in progress
              enum:
              - Success
              - Failed
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
