apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubevault
  name: vaultpolicybindings.policy.kubevault.com
spec:
  group: policy.kubevault.com
  names:
    categories:
    - vault
    - appscode
    - all
    kind: VaultPolicyBinding
    listKind: VaultPolicyBindingList
    plural: vaultpolicybindings
    shortNames:
    - vpb
    singular: vaultpolicybinding
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: 'links: https://www.vaultproject.io/api/auth/kubernetes/index.html#parameters-1'
            properties:
              policies:
                description: Policies is a list of Vault policy identifiers.
                items:
                  properties:
                    name:
                      description: 'Name is a Vault server policy name. This name
                        should be returned by `vault read sys/policy` command. More
                        info: https://www.vaultproject.io/docs/concepts/policies.html#listing-policies'
                      type: string
                    ref:
                      description: 'Ref is name of a VaultPolicy crd object. Actual
                        vault policy name is spec.vaultRoleName field. More info:
                        https://www.vaultproject.io/docs/concepts/policies.html#listing-policies'
                      type: string
                  type: object
                type: array
              subjectRef:
                description: SubjectRef refers to Vault users who will be granted
                  policies.
                properties:
                  kubernetes:
                    description: 'Kubernetes refers to Vault users who are authenticated
                      via Kubernetes auth method More info: https://www.vaultproject.io/docs/auth/kubernetes.html#configuration'
                    properties:
                      maxTTL:
                        description: Specifies the maximum allowed lifetime of tokens
                          issued in seconds using this role.
                        type: string
                      path:
                        description: 'Specifies the path where kubernetes auth is
                          enabled default : kubernetes'
                        type: string
                      period:
                        description: If set, indicates that the token generated using
                          this role should never expire. The token should be renewed
                          within the duration specified by this value. At each renewal,
                          the token's TTL will be set to the value of this parameter.
                        type: string
                      serviceAccountNames:
                        description: Specifies the names of the service account to
                          bind with policy
                        items:
                          type: string
                        type: array
                      serviceAccountNamespaces:
                        description: Specifies the namespaces of the service account
                        items:
                          type: string
                        type: array
                      ttl:
                        description: Specifies the TTL period of tokens issued using
                          this role in seconds.
                        type: string
                    required:
                    - serviceAccountNames
                    - serviceAccountNamespaces
                    type: object
                type: object
              vaultRef:
                description: VaultRef is the name of a AppBinding referencing to a
                  Vault Server
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              vaultRoleName:
                description: 'VaultRoleName is the role name which will be bound of
                  the policies This defaults to following format: k8s.${cluster}.${metadata.namespace}.${metadata.name}
                  xref: https://www.vaultproject.io/api/auth/kubernetes/index.html#create-role'
                type: string
            required:
            - policies
            - subjectRef
            - vaultRef
            type: object
          status:
            properties:
              conditions:
                description: Represents the latest available observations of a VaultPolicyBinding.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: ObservedGeneration is the most recent generation observed
                  for this resource. It corresponds to the resource's generation,
                  which is updated on mutation by the API Server.
                format: int64
                type: integer
              phase:
                description: Phase indicates whether successfully bind the policy
                  to service account in vault or not or in progress
                enum:
                - Success
                - Failed
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
