apiVersion: engine.kubevault.com/v1alpha1
kind: HazelcastRole
metadata:
  name: hazelcast-app-role
  namespace: demo
spec:
  secretEngineRef:
    name: hazelcast-engine
  defaultTTL: 24h
  maxTTL: 168h
