apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: hazelcast-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  hazelcast:
    databaseRef:
      name: hazelcast
      namespace: demo
    pluginName: hazelcast-database-plugin
    allowedRoles:
    - "*"
