apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: milvus-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  milvus:
    databaseRef:
      name: milvus
      namespace: demo
    pluginName: milvus-database-plugin
    allowedRoles:
      - "*"
    dbName: default
    insecure: false
