apiVersion: engine.kubevault.com/v1alpha1
kind: MilvusRole
metadata:
  name: milvus-superuser-role
  namespace: demo
spec:
  secretEngineRef:
    name: milvus-engine
  creationStatements:
    - '{"roles":["dba","readonly"]}'
  defaultTTL: 1h
  maxTTL: 24h
