apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: mssqlserver-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  mssqlserver:
    databaseRef:
      name: mssqlserver
      namespace: demo
    pluginName: mssql-database-plugin
    allowedRoles:
      - "*"
    maxOpenConnections: 4
    maxIdleConnections: 0
    maxConnectionLifetime: 0s
