apiVersion: engine.kubevault.com/v1alpha1
kind: MSSQLServerRole
metadata:
  name: mssqlserver-superuser-role
  namespace: demo
spec:
  secretEngineRef:
    name: mssqlserver-engine
  creationStatements:
    - |
      CREATE LOGIN [{{name}}] WITH PASSWORD = '{{password}}';
      CREATE USER [{{name}}] FOR LOGIN [{{name}}];
      GRANT SELECT ON SCHEMA::dbo TO [{{name}}];
  defaultTTL: 1h
  maxTTL: 24h
