/*
Copyright The KubeVault Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubevault.dev/operator/apis/approle/v1alpha1"
	scheme "kubevault.dev/operator/client/clientset/versioned/scheme"
)

// VaultAppRolesGetter has a method to return a VaultAppRoleInterface.
// A group's client should implement this interface.
type VaultAppRolesGetter interface {
	VaultAppRoles(namespace string) VaultAppRoleInterface
}

// VaultAppRoleInterface has methods to work with VaultAppRole resources.
type VaultAppRoleInterface interface {
	Create(*v1alpha1.VaultAppRole) (*v1alpha1.VaultAppRole, error)
	Update(*v1alpha1.VaultAppRole) (*v1alpha1.VaultAppRole, error)
	UpdateStatus(*v1alpha1.VaultAppRole) (*v1alpha1.VaultAppRole, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.VaultAppRole, error)
	List(opts v1.ListOptions) (*v1alpha1.VaultAppRoleList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VaultAppRole, err error)
	VaultAppRoleExpansion
}

// vaultAppRoles implements VaultAppRoleInterface
type vaultAppRoles struct {
	client rest.Interface
	ns     string
}

// newVaultAppRoles returns a VaultAppRoles
func newVaultAppRoles(c *ApproleV1alpha1Client, namespace string) *vaultAppRoles {
	return &vaultAppRoles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vaultAppRole, and returns the corresponding vaultAppRole object, and an error if there is any.
func (c *vaultAppRoles) Get(name string, options v1.GetOptions) (result *v1alpha1.VaultAppRole, err error) {
	result = &v1alpha1.VaultAppRole{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vaultapproles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VaultAppRoles that match those selectors.
func (c *vaultAppRoles) List(opts v1.ListOptions) (result *v1alpha1.VaultAppRoleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VaultAppRoleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vaultapproles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vaultAppRoles.
func (c *vaultAppRoles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vaultapproles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a vaultAppRole and creates it.  Returns the server's representation of the vaultAppRole, and an error, if there is any.
func (c *vaultAppRoles) Create(vaultAppRole *v1alpha1.VaultAppRole) (result *v1alpha1.VaultAppRole, err error) {
	result = &v1alpha1.VaultAppRole{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vaultapproles").
		Body(vaultAppRole).
		Do().
		Into(result)
	return
}

// Update takes the representation of a vaultAppRole and updates it. Returns the server's representation of the vaultAppRole, and an error, if there is any.
func (c *vaultAppRoles) Update(vaultAppRole *v1alpha1.VaultAppRole) (result *v1alpha1.VaultAppRole, err error) {
	result = &v1alpha1.VaultAppRole{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vaultapproles").
		Name(vaultAppRole.Name).
		Body(vaultAppRole).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *vaultAppRoles) UpdateStatus(vaultAppRole *v1alpha1.VaultAppRole) (result *v1alpha1.VaultAppRole, err error) {
	result = &v1alpha1.VaultAppRole{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vaultapproles").
		Name(vaultAppRole.Name).
		SubResource("status").
		Body(vaultAppRole).
		Do().
		Into(result)
	return
}

// Delete takes name of the vaultAppRole and deletes it. Returns an error if one occurs.
func (c *vaultAppRoles) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vaultapproles").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vaultAppRoles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vaultapproles").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched vaultAppRole.
func (c *vaultAppRoles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VaultAppRole, err error) {
	result = &v1alpha1.VaultAppRole{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vaultapproles").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
