apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: hanadb-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  hanadb:
    databaseRef:
      name: hanadb
      namespace: demo
    pluginName: hana-database-plugin
    allowedRoles:
      - "*"
    maxOpenConnections: 4
    maxIdleConnections: 0
