apiVersion: engine.kubevault.com/v1alpha1
kind: HanaDBRole
metadata:
  name: hanadb-readonly
  namespace: demo
spec:
  secretEngineRef:
    name: hanadb-engine
  creationStatements:
    - |
      CREATE USER "{{name}}" PASSWORD "{{password}}" NO FORCE_FIRST_PASSWORD_CHANGE VALID UNTIL '{{expiration}}';
      GRANT SELECT ON SCHEMA APP TO "{{name}}";
  defaultTTL: 1h
  maxTTL: 24h
