apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: qdrant-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  qdrant:
    databaseRef:
      name: qdrant
      namespace: demo
    pluginName: qdrant-database-plugin
    allowedRoles:
    - "*"
