apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: oracle-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  oracle:
    databaseRef:
      name: oracle
      namespace: demo
    pluginName: oracle-database-plugin
    allowedRoles:
      - "*"
    maxOpenConnections: 4
    maxIdleConnections: 0
    maxConnectionLifetime: 0s
