apiVersion: engine.kubevault.com/v1alpha1
kind: OracleRole
metadata:
  name: oracle-superuser-role
  namespace: demo
spec:
  secretEngineRef:
    name: oracle-engine
  creationStatements:
    - |
      CREATE USER {{name}} IDENTIFIED BY "{{password}}";
      GRANT CONNECT, RESOURCE TO {{name}};
  revocationStatements:
    - DROP USER {{name}} CASCADE;
  defaultTTL: 1h
  maxTTL: 24h
