apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: weaviate-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  weaviate:
    databaseRef:
      name: weaviate
      namespace: demo
    pluginName: weaviate-database-plugin
    allowedRoles:
    - "*"
