apiVersion: engine.kubevault.com/v1alpha1
kind: SecretRoleBinding
metadata:
  name: secret-role-binding
  namespace: demo
spec:
  roles:
    - kind: DB2Role
      name: db2-app-role
  subjects:
    - kind: ServiceAccount
      name: test-user-account
      namespace: demo
