apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: db2-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  db2:
    databaseRef:
      name: db2
      namespace: demo
    pluginName: db2-database-plugin
    allowedRoles:
    - "*"
