apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-pkicreds-binding
  namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: pki-vault
  namespace: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pki-vault
  namespace: demo