apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: mysql-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  mysql:
    databaseRef:
      name: mysql
      namespace: demo
    pluginName: "mysql-database-plugin"
