apiVersion: engine.kubevault.com/v1alpha1
kind: MySQLRole
metadata:
  name: mysql-superuser-role
  namespace: demo
spec:
  vaultRef:
    name: vault
  databaseRef:
    name: mysql
    namespace: demo
  path: "your-database-path"
  creationStatements:
    - "CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';"
    - "GRANT SELECT ON *.* TO '{{name}}'@'%';"
  defaultTTL: 1h
  maxTTL: 24h
