apiVersion: engine.kubevault.com/v1alpha1
kind: KafkaRole
metadata:
  name: kafka-superuser-role
  namespace: demo
spec:
  secretEngineRef:
    name: kafka-engine
  creationStatements:
    - '{"mechanism":"SCRAM-SHA-256","acls":[{"resource_type":"TOPIC","resource_name":"*","operation":"ALL","permission":"ALLOW"},{"resource_type":"GROUP","resource_name":"*","operation":"ALL","permission":"ALLOW"}]}'
  defaultTTL: 1h
  maxTTL: 24h
