apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: kafka-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  kafka:
    databaseRef:
      name: kafka
      namespace: demo
    pluginName: kafka-database-plugin
    allowedRoles:
      - "*"
    mechanism: SCRAM-SHA-256
    useTLS: false
    insecure: false
