apiVersion: engine.kubevault.com/v1alpha1
kind: SecretRoleBinding
metadata:
  name: secret-r-binding
  namespace: dev
spec:
  roles:
    - kind: AWSRole
      name: aws-role
  subjects:
    - kind: ServiceAccount
      name: test-user-account
      namespace: demo