/*
Copyright 2018 The Kube Vault Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubevault/operator/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVaultserverVersions implements VaultserverVersionInterface
type FakeVaultserverVersions struct {
	Fake *FakeCoreV1alpha1
}

var vaultserverversionsResource = schema.GroupVersionResource{Group: "core.kubevault.com", Version: "v1alpha1", Resource: "vaultserverversions"}

var vaultserverversionsKind = schema.GroupVersionKind{Group: "core.kubevault.com", Version: "v1alpha1", Kind: "VaultserverVersion"}

// Get takes name of the vaultserverVersion, and returns the corresponding vaultserverVersion object, and an error if there is any.
func (c *FakeVaultserverVersions) Get(name string, options v1.GetOptions) (result *v1alpha1.VaultserverVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(vaultserverversionsResource, name), &v1alpha1.VaultserverVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultserverVersion), err
}

// List takes label and field selectors, and returns the list of VaultserverVersions that match those selectors.
func (c *FakeVaultserverVersions) List(opts v1.ListOptions) (result *v1alpha1.VaultserverVersionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(vaultserverversionsResource, vaultserverversionsKind, opts), &v1alpha1.VaultserverVersionList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VaultserverVersionList{ListMeta: obj.(*v1alpha1.VaultserverVersionList).ListMeta}
	for _, item := range obj.(*v1alpha1.VaultserverVersionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vaultserverVersions.
func (c *FakeVaultserverVersions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(vaultserverversionsResource, opts))
}

// Create takes the representation of a vaultserverVersion and creates it.  Returns the server's representation of the vaultserverVersion, and an error, if there is any.
func (c *FakeVaultserverVersions) Create(vaultserverVersion *v1alpha1.VaultserverVersion) (result *v1alpha1.VaultserverVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(vaultserverversionsResource, vaultserverVersion), &v1alpha1.VaultserverVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultserverVersion), err
}

// Update takes the representation of a vaultserverVersion and updates it. Returns the server's representation of the vaultserverVersion, and an error, if there is any.
func (c *FakeVaultserverVersions) Update(vaultserverVersion *v1alpha1.VaultserverVersion) (result *v1alpha1.VaultserverVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(vaultserverversionsResource, vaultserverVersion), &v1alpha1.VaultserverVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultserverVersion), err
}

// Delete takes name of the vaultserverVersion and deletes it. Returns an error if one occurs.
func (c *FakeVaultserverVersions) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(vaultserverversionsResource, name), &v1alpha1.VaultserverVersion{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVaultserverVersions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(vaultserverversionsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.VaultserverVersionList{})
	return err
}

// Patch applies the patch and returns the patched vaultserverVersion.
func (c *FakeVaultserverVersions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VaultserverVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(vaultserverversionsResource, name, data, subresources...), &v1alpha1.VaultserverVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultserverVersion), err
}
