apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: druid-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  druid:
    databaseRef:
      name: druid
      namespace: demo
    pluginName: druid-database-plugin
    allowedRoles:
      - "*"
    authenticator: MyBasicMetadataAuthenticator
    authorizer: MyBasicMetadataAuthorizer
