apiVersion: engine.kubevault.com/v1alpha1
kind: DruidRole
metadata:
  name: druid-superuser-role
  namespace: demo
spec:
  secretEngineRef:
    name: druid-engine
  creationStatements:
    - '{"roles":["role1","role2"]}'
  defaultTTL: 1h
  maxTTL: 24h
