apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: zookeeper-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  zookeeper:
    databaseRef:
      name: zookeeper
      namespace: demo
    pluginName: zookeeper-database-plugin
    allowedRoles:
    - "*"
