apiVersion: engine.kubevault.com/v1alpha1
kind: ZooKeeperRole
metadata:
  name: zookeeper-app-role
  namespace: demo
spec:
  secretEngineRef:
    name: zookeeper-engine
  defaultTTL: 24h
  maxTTL: 168h
