apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: postgres-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  mysql:
    databaseRef:
      name: postgres
      namespace: demo
    pluginName: "postgresql-database-plugin"
