{
 "title": "Vault Cluster Health",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Vault Cluster",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(vault_info) by (vault_cluster, kubernetes_namespace)",
     "legendFormat": "Vault Cluser : {{ kubernetes_namespace }}/{{vault_cluster}}"
    }
   ]
  },
  {
   "title": "Up Instances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vault_up) by ( vault_cluster, pod_name, kubernetes_namespace)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Down Instances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(1 - vault_up) by ( vault_cluster, pod_name, kubernetes_namespaces)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Initialized Instances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vault_initialized) by ( vault_cluster, pod_name, kubernetes_namespace)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Unsealed Instances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(1 - vault_sealed) by (vault_cluster, pod_name, kubernetes_namespace)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Sealed Instances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vault_sealed) by (vault_cluster, pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Runtime Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(vault_runtime_alloc_bytes) by (vault_cluster)",
     "legendFormat": "allocated_bytes : {{ vault_cluster }}"
    },
    {
     "expr": "max(vault_runtime_sys_bytes) by (vault_cluster)",
     "legendFormat": "system_bytes : {{ vault_cluster }}"
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(vault_runtime_total_gc_pause_ns / 1000000 ) by (vault_cluster)",
     "legendFormat": "{{vault_cluster}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_route_count[1m])) by (vault_cluster)",
     "legendFormat": "{{vault_cluster}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(vault_route{quantile=\"0.99\"}) by (vault_cluster)",
     "legendFormat": "99th Percentile : {{vault_cluster}}"
    },
    {
     "expr": "max(vault_route{quantile=\"0.5\"}) by (vault_cluster)",
     "legendFormat": "50th Percentile : {{vault_cluster}}"
    },
    {
     "expr": "sum(rate(vault_route_sum[5m])) by (vault_cluster) / sum(rate(vault_route_count[5m])) by (vault_cluster)",
     "legendFormat": "Average : {{vault_cluster}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vault_runtime_num_goroutines)",
     "legendFormat": "vault_cluster : {{vault_cluster}}"
    }
   ]
  },
  {
   "title": "Modify by Path",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vault_route_count{method=~\"create|delete|renew\"}[5m])) by (method, path)",
     "legendFormat": "{{ method }} : {{path}}"
    }
   ]
  },
  {
   "title": "Read by Path",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vault_route_count{method=~\"read\"}[5m])) by (method, path)",
     "legendFormat": "{{ method }} : {{path}}"
    }
   ]
  },
  { "title": "Token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Pending Tokens",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "vault_token_create_count - vault_token_store_count"
    }
   ]
  },
  {
   "title": "Token Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_token_lookup_count[1m])) by (vault_cluster)",
     "legendFormat": "Lookup : {{vault_cluster}}"
    }
   ]
  },
  {
   "title": "Token",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vault_token_create_count) by (vault_cluster)",
     "legendFormat": "Create : {{vault_cluster}}"
    },
    {
     "expr": "sum(vault_token_store_count) by (vault_cluster)",
     "legendFormat": "Store : {{vault_cluster}}"
    }
   ]
  },
  { "title": "Audit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Audit Log Request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vault_audit_log_request_count[1m])) by (vault_cluster)",
     "legendFormat": "Request : {{vault_cluster}}"
    },
    {
     "expr": "sum(irate(vault_audit_log_response_count[1m])) by (vault_cluster)",
     "legendFormat": "Response : {{vault_cluster}}"
    },
    {
     "expr": "sum(irate(vault_core_handle_request_count[1m])) by (vault_cluster)",
     "legendFormat": "Handled : {{vault_cluster}}"
    }
   ]
  },
  {
   "title": "Auth Rollback",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vault_route_count{method=~\"rollback\"}[5m])) by (method, path)",
     "legendFormat": "{{ method }}:{{path}}"
    }
   ]
  },
  { "title": "Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Policy Set",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_policy_set_policy_count[1m])) by (vault_cluster)",
     "legendFormat": "set : {{ vault_cluster }}"
    }
   ]
  },
  {
   "title": "Policy Get",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_policy_get_policy_count[1m])) by (vault_cluster)",
     "legendFormat": "get : {{ vault_cluster }}"
    }
   ]
  },
  { "title": "Database Secret Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Num of Databases",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 51 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "vault_database_initialize_total - vault_database_close_total"
    }
   ]
  },
  {
   "title": "Database Initialize and Close Error",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vault_database_initialize_error_total[5m])",
     "legendFormat": "create_error"
    },
    {
     "expr": "rate(vault_database_close_error_total[5m])",
     "legendFormat": "renew_error"
    }
   ]
  },
  {
   "title": "Active User",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 51 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "vault_database_user_create_total - vault_database_user_revoke_total"
    }
   ]
  },
  {
   "title": "User Create, Renew and Revoke Error",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vault_database_user_create_error_total[5m])",
     "legendFormat": "create_error"
    },
    {
     "expr": "rate(vault_database_user_renew_error_total[5m])",
     "legendFormat": "renew_error"
    },
    {
     "expr": "rate(vault_database_user_revoke_error_total[5m])",
     "legendFormat": "revoke_error"
    }
   ]
  },
  { "title": "Google Cloud Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Cloud Storage List",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(irate(vault_gcs_list_count[10m]))",
     "legendFormat": "list"
    }
   ]
  },
  {
   "title": "Cloud Storage GET",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(vault_gcs_get_count[10m])", "legendFormat": "GET" }
   ]
  },
  {
   "title": "Cloud Storage Delete",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vault_gcs_delete_count[10m])",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "Cloud Storage PUT",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(vault_gcs_put_sum[5m])", "legendFormat": "PUT" }
   ]
  },
  { "title": "Amazon S3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "S3 Storage List",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(irate(vault_s3_list_count[10m]))",
     "legendFormat": "list"
    }
   ]
  },
  {
   "title": "S3  Storage GET",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(vault_s3_get_count[10m])", "legendFormat": "GET" }
   ]
  },
  {
   "title": "S3 Storage Delete",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vault_s3_delete_count[10m])",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "S3 Storage PUT",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(vault_s3_put_sum[5m])", "legendFormat": "PUT" }
   ]
  },
  { "title": "Microsoft Azure Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Azure Storage List",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(irate(vault_azure_list_count[10m]))",
     "legendFormat": "list"
    }
   ]
  },
  {
   "title": "Azure  Storage GET",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vault_azure_get_count[10m])",
     "legendFormat": "GET"
    }
   ]
  },
  {
   "title": "Azure Storage Delete",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vault_azure_delete_count[10m])",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "Azure Storage PUT",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(vault_azure_put_sum[5m])", "legendFormat": "PUT" }
   ]
  }
 ]
}