apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-db-provider
  namespace: demo
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.demo:8200"
    roleName: "k8s.-.demo.azure-reader-role"
    objects: |
      - objectName: "client_id"
        secretPath: "your-azure-path/creds/k8s.-.demo.azure-role"
        secretKey: "client_id"
      - objectName: "client_secret"
        secretPath: "your-azure-path/creds/k8s.-.demo.azure-role"
        secretKey: "client_secret"