apiVersion: engine.kubevault.com/v1alpha1
kind: SecretRoleBinding
metadata:
  name: secret-role-binding
  namespace: demo
spec:
  roles:
    - kind: AzureRole
      name: azure-role
  subjects:
    - kind: ServiceAccount
      name: test-user-account
      namespace: demo
