apiVersion: v1
kind: Pod
metadata:
  name: test-app
  namespace: demo
spec:
  serviceAccountName: pod-sa
  containers:
    - image: jweissig/app:0.0.1
      name: test-app
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets-store/test"
          readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "vault-database"
